# Configuration du serveur
server.port=8081

# Configuration de la source de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/prevention_db
spring.datasource.username=fosmef_user
spring.datasource.password=fosmef_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' va créer ou modifier automatiquement les tables en fonction de vos entités Java
spring.jpa.hibernate.ddl-auto=update

# Affichage des requêtes SQL dans la console (pratique pour le développement)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Désactivation temporaire de la sécurité stricte sur toutes les routes pour les tests initiaux
# (À affiner lors de l'intégration finale de Spring Security / JWT)
spring.security.user.name=admin
spring.security.user.password=admin_password

# Configuration de la sécurité JWT
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000